### ISSUE TITLE
Cannot find module for adjacent package

### ISSUE THREAD

**Issue by neary-humane** [Butterwire/serverless-plugin-monorepo#31]
Hi @martin-css — thanks for putting this up. I am sure I'm missing something obvious, but am getting a `Cannot find module` error.

1. `packages/background-sync/package.json` lists `"@humane/networking": "1.0.0",` under "dependencies"
2. `packages/background-sync/serverless.yml` includes `serverless-plugin-monorepo` as a plugin
3. `packages/networking/package.json` has name `@humane/networking` and version `"1.0.0"`

We are using yarn workspaces without any `nohoist` features. We have a handful of apps, and they are all able to import from `@humane/networking`, but `background-sync` is our first serverless project.

It seems like it's able to figure out node_module imports. Am I missing something? Does anything stand out to you? How might you go about diagnosing this? Thanks so much!

**Comment by timpetri** [comment]
Were you able to solve this? Running into the same issue. 

After running the symlinking into the package-local node_modules, I can see that the requested package is there, and it's referenced under "packing external modules: @internal/package@1.0.0", but I get the error 

`Error: yarn install --non-interactive --frozen-lockfile failed with code 1`

and the detailed yarn-error.log in .webpack/dependencies gives me a trace where it appears to try to find this in the yarnpkg registry:

```
Trace: 
  Error: https://registry.yarnpkg.com/@internal%package: Not found
      at Request.params.callback [as _callback] (/Users/timpetri/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:66145:18)
      at Request.self.callback (/Users/timpetri/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:526:28)
      at Request.<anonymous> (/Users/timpetri/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:526:28)
      at IncomingMessage.<anonymous> (/Users/timpetri/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:645:28)
      at IncomingMessage.emit (node:events:538:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
