### ISSUE TITLE
it needs support for pnpm

### ISSUE THREAD

**Issue by guhyeon** [Butterwire/serverless-plugin-monorepo#40]
I'm working with pnpm, and

pnpm options
` .npmrc 
node-linker = hoisted
hoist-pattern[]=!@my-project
`

but I failed because of 
not hoisted packages in @my-project.

`Error:
│ Error: Cannot find module './@my-project\common\package.json'
│ Require stack:
│ - my-project\node_modules\serverless-plugin-monorepo\lib\index.js
│ - my-project\node_modules\serverless\lib\utils\require-with-import-fallback.js
│ - my-project\node_modules\serverless\lib\classes\plugin-manager.js
│ - my-project\node_modules\serverless\lib\serverless.js
│ - my-project\node_modules\serverless\scripts\serverless.js
│ - my-project\node_modules\serverless\bin\serverless.js
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
│     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
│     at ServerlessMonoRepo.linkPackage (my-project\node_modules\serverless-plugin-monorepo\lib\index.js:77:29)
│     at my-project\node_modules\serverless-plugin-monorepo\lib\index.js:126:72
│     at Array.map (<anonymous>)
│     at ServerlessMonoRepo.initialise (my-project\node_modules\serverless-plugin-monorepo\lib\index.js:126:53)
│     at package:initialize (my-project\node_modules\serverless-plugin-monorepo\lib\index.js:51:46)
│     at PluginManager.runHooks (my-project\node_modules\serverless\lib\classes\plugin-manager.js:530:15)
│     at async PluginManager.invoke (my-project\node_modules\serverless\lib\classes\plugin-manager.js:564:9)
│     at async PluginManager.spawn (my-project\node_modules\serverless\lib\classes\plugin-manager.js:585:5)
│     at async before:deploy:deploy (my-project\node_modules\serverless\lib\plugins\deploy.js:40:11)
│     at async PluginManager.runHooks (my-project\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
│     at async PluginManager.invoke (my-project\node_modules\serverless\lib\classes\plugin-manager.js:563:9)
│     at async PluginManager.run (my-project\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
│     at async Serverless.run (my-project\node_modules\serverless\lib\serverless.js:179:5)
│     at async my-project\node_modules\serverless\scripts\serverless.js:834:9
`

**Comment by guhyeon** [comment]
This repository seems to not managed,
So I make new project see bellow.

https://github.com/guhyeon/serverless-plugin-monorepo3
